"""Annotation workflow: schemas, import/export, and Label Studio integration."""

from __future__ import annotations

from pickup_putdown.annotation.import_export import (
    MetadataLoadStats,
    build_candidate_tasks,
    build_label_studio_tasks,
    check_media_references,
    convert_candidates_to_predictions,
    export_candidate_annotations,
    export_events_csv,
    export_ignore_intervals_parquet,
    select_candidate_pilot,
    validate_candidate_metadata,
    validate_export,
)
from pickup_putdown.annotation.schemas import (
    AnnotationEvent,
    AnnotationRegion,
    AnnotationUnit,
    CandidateMetadata,
    CandidateValidationError,
    CanonicalEvent,
    ConversionResult,
    IgnoreIntervalExport,
    LabelStudioPrediction,
    LabelStudioTask,
    MediaCheckReport,
    MediaCheckResult,
    ReviewMetadata,
    ValidationErrors,
    VideoUrlMode,
)

__all__ = [
    "AnnotationEvent",
    "AnnotationRegion",
    "AnnotationUnit",
    "CandidateMetadata",
    "CandidateValidationError",
    "CanonicalEvent",
    "ConversionResult",
    "IgnoreIntervalExport",
    "LabelStudioTask",
    "LabelStudioPrediction",
    "MetadataLoadStats",
    "MediaCheckReport",
    "MediaCheckResult",
    "ReviewMetadata",
    "ValidationErrors",
    "VideoUrlMode",
    "build_candidate_tasks",
    "build_label_studio_tasks",
    "check_media_references",
    "convert_candidates_to_predictions",
    "export_candidate_annotations",
    "export_events_csv",
    "export_ignore_intervals_parquet",
    "select_candidate_pilot",
    "validate_candidate_metadata",
    "validate_export",
]
